### ISSUE TITLE
Some polishing needed for fresh install

### ISSUE THREAD

**Issue by Maxximus007** [hossbeast/autominer#1]
Hi,

Was checking out your autoswitcher. Looking nice but: Have a few remarks for now (Ubuntu 16.04).
#!/bin/env gives issues -> #!/usr/bin/env

Needed to install:
sudo apt-get install libjson-xs-perl

First start nicehash-aggegrator searches for non-existent directories:
.autominer/config) : No such file or directory
.autominer/data/rates/nicehash/samples) : No such file or directory

Did this manually.

It seems that nicehash-aggegrator needs to run indefenenitly?

Hope it helps.

PS Where do you expect the miners to live?

**Comment by hossbeast** [comment]
Cool, thanks. I have a ubuntu laptop, I'll run through a fresh install on there and fix these issues. Probably add some per-distro instructions to the README.

For the miners themselves, the expectation is that they've been properly installed and are therefore available somewhere in $PATH. I could potentially also support a configuration key with the full path to the executable, in case of not-yet-installed binaries.

**Comment by hossbeast** [comment]
I pushed commits to master which address the shebang, directory creation, and explanation of installing dependencies.

I created issue #2 to track an idea I have about running nicehash-aggregator automatically.

Yeah, for now, you need to run nicehash-aggregator separately and keep it running.

**Comment by Maxximus007** [comment]
Okay great! I'd very much like to see a config key for the path to a miner, several miners (and versions) share the same name, so I personally don't install them in $PATH.

And some extra ideas for config keys: location and worker name:
LOCATION can be "eu", "usa", "hk" or "jp" (see also this FAQ), YOUR-BITCOIN-ADDRESS is your Bitcoin address, used for mining, WORKER-NAME is optional to name your rig.
I'm in EU so like to set location at least.

**Comment by hossbeast** [comment]
Yeah, those options make sense. I created new issues to track.
