### ISSUE TITLE
Differences between autominers?

### ISSUE THREAD

**Issue by aro28** [hossbeast/autominer#16]
Hi @hossbeast 
What is the differences between "hossbeast/autominer" and "autominer/autominer", which is placed on
https://github.com/autominer/autominer

Thanks in advance!
Best,
Aro28

**Comment by hossbeast** [comment]
Looks like autominer/autominer only supports direct coin mining, while hossbeast/autominer only supports selling your hashrate on nicehash.

The changes I'm working on on the wip branch will soon enable direct mining with hossbeast/autominer via miningpoolhub, but it won't be either/or. You'll be able to setup both, and seamlessly switch between them depending on what's profitable.

hossbeast/autominer also has some pretty good analysis tools to e.g. view the history of mining choices, compare predicted profit to actual profit, etc.
