### ISSUE TITLE
run nicehash-aggregator on demand

### ISSUE THREAD

**Issue by hossbeast** [hossbeast/autominer#2]
To make it easier for users, launch nicehash-aggregator from autominer-mine when necessary. This solves the base case, for users that only run a single autominer instance.

For users that run multiple copies of autominer with different profiles, use a lock to avoid running multiple instances of nicehash-aggregator.

Retain the ability to run nicehash-aggregator independently, and make that the recommendation for users that run multiple autominers under different profiles.

**Comment by Maxximus007** [comment]
Perhaps the other way around: check if nicehash-aggregator is already running (ps -ef | awk '$NF~"nicehash-aggregator" {print $2}'), if not launch in background?

**Comment by hossbeast** [comment]
close to that - if you haven't intentionally run it independently, then it should terminate when the autominer process which on-demand spawned it terminates.
